### ISSUE TITLE
[Issue 2] Letter

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#108]
Assuming you're doing another of these, this can be posted here:

https://github.com/midnightbreakfast/web/blob/magazine/_src/pages/issue2/letter.md

Should be pretty straightforward.

**Comment by rebeccarubenstein** [comment]
I'll be dealing with this tomorrow morning/throughout the day, and I'll let you know once it's ready.

**Comment by nevanscott** [comment]
Just a heads up: it's looking like everything else is up and running. Depending on when you finish this, I may be out and about, possibly getting dinner. So you might need to ping me.

You can do it!

**Comment by rebeccarubenstein** [comment]
@nevanscott Thanks for the support. Hoping to have this done in the next hour. I am just having that thing happen where everything I write feels like bullshit. :(

**Comment by rebeccarubenstein** [comment]
@nevanscott Okay, it's finally in there. I'm also moving the draft to the MB folder, in case you have any comments/suggestions for things to change:

https://docs.google.com/document/d/1Zwa4kGmviKMPXoDofevAiturUqle0RgNGVr7Zo8YuBw/edit?usp=sharing

@ftpavlik Adding you to this to alert you to the draft of the letter. Since this was so last-minute and I have no idea what your schedule's like today, if you don't have time/don't feel the need to leave comments, that's cool. To be honest, I really just needed to get this out the door — it took me forever to write for some reason, so if you _do_ have comments, it might be best for you to suggest specific line edits at this stage. I don't really have the mental energy to keep revising it.

**Comment by ftpavlik** [comment]
This is really good. My only question: should it be "American educational
system"?

**Comment by nevanscott** [comment]
Also, I put it up on the preview site...

**Comment by rebeccarubenstein** [comment]
@ftpavlik Good call. I'll make sure to make that change. And thanks -- I'll let @nevanscott weigh in, but once I've had both your okays, everything will be good to go.

**Comment by rebeccarubenstein** [comment]
@nevanscott: Don't worry about commenting. I think this is all good. Let's just push these changes and consider this issue locked. Confirm once you've done this and close this ticket, please.

**Comment by nevanscott** [comment]
I did have a chance to read it, and I think it's brilliant. Well done.

The only thing I might be picky about is that you may be overdoing it with the dashes a bit. But I don't think that's worth the fuss right now.

**Comment by rebeccarubenstein** [comment]
Thanks to the both of you, for the kindness and words of encouragement. :)

@nevanscott, like I said, I think you can just push the changes I made and call it a day. (And close this ticket.)
