### ISSUE TITLE
Mairead Case's piece: language indicating excerpt

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#132]
Because Mairead's piece is a series of vignettes excerpted from her novel <cite>See You In The Morning</cite>, let me know where/how I should add that language. It would make the most sense to drop it at the bottom, perhaps below the bio. (Maybe a field needs to be created?)

**Comment by nevanscott** [comment]
For now, call it "endnote", so at least it's in there, and I'll figure out whether it's getting placed appropriately.

**Comment by rebeccarubenstein** [comment]
Uhh, okay. I'll drop it at the end of the text, then, and you can place it where it needs to go.

**Comment by nevanscott** [comment]
I mean in that top part, like the other meta data, you know? Just called "endnote: "

**Comment by rebeccarubenstein** [comment]
Okay. Have to go out now, so I'll be doing it later, but I hope I don't fuck up the HTML.

**Comment by rebeccarubenstein** [comment]
Er, the Markdown? I don't even know. Man, I'm tired.

**Comment by rebeccarubenstein** [comment]
Added endnote. Does that text read okay to you? Mairead and I hadn't discussed it, but this is similar to how I've seen this situation handled in other contexts.

**Comment by rebeccarubenstein** [comment]
@ftpavlik I accidentally added you to this and I'm not quite sure how to unsubscribe you, so if you could unsubscribe yourself, that'd be rad. Thanks!

**Comment by nevanscott** [comment]
I'm fine with the language, but I'd really prefer to normalize to "Featherproof Books" instead of keeping with lowercase and their italics. I did some hunting around, and this is also what other sites and publications seem to have done.
- https://en.wikipedia.org/wiki/Featherproof_Books
- http://gapersblock.com/airbags/archives/jonathan_messinger_featherproof_books/
- http://decompmagazine.com/areviewofmessingershidingout.htm
- http://isgreaterthan.net/2008/02/preserving-our-independents/
- http://www.gapersblock.com/bookclub/2006/11/08/feature_featherproof_books_lig/

I realize it seems like I'm being annoying, but I really think this should be our rule of thumb in general. That way of writing out their name is how it is done in their logo, which to me means it's stylistic for marketing purposes. But I just don't like bending on capitalization and styling for organizations. We should think about where we draw the lines at some point.

I'm fine with being more lenient/liberal than my personal way of handling this usually allows, but I just think this one goes too far, especially the italics.

**Comment by rebeccarubenstein** [comment]
@nevanscott As I mentioned last night, this is totally fine with me. No pushback on my end. I've made the change. Once you've pushed it, if this looks good to you, please close the ticket.
