### ISSUE TITLE
[Issue 3] Author Bio links?

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#150]
@ftpavlik @rebeccarubenstein 

Just wanted your thoughts, since it looked to me like maybe some of the bios were missing links (like to Twitter or to other online publications), but I wasn't sure whose pieces are whose or what our policies have been around these sort of links.

Figured I'd hand it over to you guys to investigate and let me know what you think.

If it does make sense to add more links, let me know when they're ready to go, and I can push to the Preview site again...

**Comment by ftpavlik** [comment]
@rebeccarubenstein @nevanscott What links are missing? The author bios for my pieces look good.

**Comment by rebeccarubenstein** [comment]
@nevanscott @ftpavlik I think what might be happening: certain writers wanted publications linked and certain writers didn't. What we've been doing with issues is deferring to writerly preferences, rather than overwhelming bios with a million links if we don't have to. All names have been linked to Twitter accounts, which is why certain Twitter handles aren't linked. Make sense?

**Comment by ftpavlik** [comment]
@rebeccarubenstein What do you mean by "all names have been linked to Twitter accounts"? Neither of my author names in the bios link to their Twitter. They link to what they sent me in their bios.

**Comment by rebeccarubenstein** [comment]
Ah, I didn't realize. Okay, well regardless, we've dealt with all the links as they need to be. My bios look fine, as well.

@nevanscott Can you close this ticket if you're cool with our answers? Bios are good to go.
