### ISSUE TITLE
Text smooshing

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#171]
Please try and fix the text smooshing. I **think** what's happening is that text that precedes text with an < em > tag is being smooshed together with that text. That's the only pattern I've found so far. So:

TEXT<em>text</em>

**Comment by rebeccarubenstein** [comment]
![weltschmerz](https://cloud.githubusercontent.com/assets/4043562/4433382/63d22fd8-46d6-11e4-93a6-eabb24dd4df9.png)

Maybe this will help...

**Comment by rebeccarubenstein** [comment]
@nevanscott Just to follow up on this: Taylor and I have gone through every piece in our archive and Issue 4 and have sorted out any/all text smoosh instances. So, I'd say make this a to-do item post-Issue 4 launch.

**Comment by nevanscott** [comment]
OK, I'll leave this for now. Thanks for the heads up!

**Comment by nevanscott** [comment]
Because ya'll did this in the WYSIWYG editor, there really isn't anything I can do anymore anyway without accidentally messing up what you guys did. The resulting code is a little gnarly right now, but I think we should leave it if it looks right. Maybe sometime down the road we can do a better cleanup job.

**Comment by rebeccarubenstein** [comment]
If it ain't broke right now, I'm not really in the mood to fix it. Closing this out.
