### ISSUE TITLE
Fix Headings style in Things I Lost in the Move

### ISSUE THREAD

**Issue by rebeccarubenstein** [midnightbreakfast/web#176]
I feel like it would look better if there was at least one more line of space between each section (without creating a section divide), so the text doesn't run together visually as much. What do you think?

**Comment by nevanscott** [comment]
@ftpavlik Those headings should really be marked as H2s, which can be done by changing the paragraph style to "Heading 2". I did it for the first two, as well as the Works Cited heading. Could you do for the rest? (I prefer that they not be in all caps, since this is our style for these kind of heading.)

**Comment by nevanscott** [comment]
@rebeccarubenstein If those headings are used, extra space will be inserted since that's what those do...

**Comment by nevanscott** [comment]
@ftpavlik If you don't have time, just shoot this back over to me.

**Comment by ftpavlik** [comment]
@nevanscott On it.
