### ISSUE TITLE
Citation at end of Things I Lost in the Move

### ISSUE THREAD

**Issue by ftpavlik** [midnightbreakfast/web#179]
@nevanscott @rebeccarubenstein I added the citations at the end of Things I Lost in the Move. Let me know if it looks correct. The quoted titles are a magazine article, a poem, and a film, respectively, so I think the style is correct.

**Comment by rebeccarubenstein** [comment]
I alphabetized them (there was something about the Guy Debord citations being broken up that wasn't sitting well with me) and italicized the Debord film title, since film titles are citations. 

@nevanscott There are a bunch of quotation marks you're going to want to fix. I forget what they're called, but they're the ones you hate. They're mainly in the Psychogeography sections, and then in the "Works cited" endnote. Example:

![screen shot 2014-09-28 at 7 05 03 pm](https://cloud.githubusercontent.com/assets/4043562/4436640/29edabba-477d-11e4-971f-8009b9393a0a.png)

**Comment by ftpavlik** [comment]
@nevanscott I fixed the straight quotes. But is there a way to make the horizontal line I added be left-ruled so it doesn't look weird next to the other left-ruled line? That or something else we can do to distinguish the citations from the contributors?

**Comment by nevanscott** [comment]
It's not perfect, but I just removed the `<hr>` since the heading style bumps it down some. I think it looks better this way than with the centered line. What do you think?

**Comment by ftpavlik** [comment]
@nevanscott I think we must have been working on the piece simultaneously, because the line was still there. I took it out and I agree, but do you mind giving it a once-over to make sure I didn't overwrite any other changes?

**Comment by nevanscott** [comment]
I just had a look, and it looks good to me this way. Why don't you take one last look to be sure nothing got lost in the mix. I kind of forgot we might run into this problem...

**Comment by ftpavlik** [comment]
@nevanscott Looks good!
